# Generated byte arrays are linked into rat_engine; installed frontends need no
# source-tree shader path. Host shaderc is built only with the renderer enabled.
set(_rat_surface_shader_dir "${CMAKE_CURRENT_SOURCE_DIR}/shaders")
set(_rat_surface_shader_out "${CMAKE_CURRENT_BINARY_DIR}/generated_shaders")
foreach(_shader IN ITEMS vs_surface fs_surface vs_contour fs_contour)
  if(_shader MATCHES "^vs_")
    set(_stage vertex)
  else()
    set(_stage fragment)
  endif()
  set(_backends glsl spirv)
  if(WIN32)
    list(APPEND _backends dxbc)
  endif()
  foreach(_backend IN LISTS _backends)
    set(_platform linux)
    if(_backend STREQUAL glsl)
      set(_profile 150)
    elseif(_backend STREQUAL spirv)
      set(_profile spirv)
    else()
      set(_platform windows)
      set(_profile s_5_0)
    endif()
    set(_output "${_rat_surface_shader_out}/${_shader}_${_backend}.bin.h")
    add_custom_command(OUTPUT "${_output}"
      COMMAND $<TARGET_FILE:shaderc> -f "${_rat_surface_shader_dir}/${_shader}.sc"
        -o "${_output}" --type ${_stage} --platform ${_platform} -p ${_profile}
        -i "${bgfx_cmake_SOURCE_DIR}/bgfx/src"
        --varyingdef "${_rat_surface_shader_dir}/varying.def.sc"
        --bin2c "${_shader}_${_backend}"
      DEPENDS shaderc "${_rat_surface_shader_dir}/${_shader}.sc"
        "${_rat_surface_shader_dir}/varying.def.sc"
        "${bgfx_cmake_SOURCE_DIR}/bgfx/src/bgfx_shader.sh"
      VERBATIM)
    target_sources(rat_engine PRIVATE "${_output}")
  endforeach()
endforeach()
